export function selectBook(book) {
  // console.log('A book has been selected:', book.title);
  // selectBook is and action creator and needs to return the action object with a type property
  // actions usually have 2 values: type and payload
  // type describes the purpose of the action
  // payload clarifies conditions of the action thats being triggered
  return {
    type: 'BOOK_SELECTED', //describes the purpose of the action use string for type just for now
    payload: book // piece of data that describes the action that is being undertaken
  };
}

// action creator is function that returns an object
// 1 write action creator, 2 wire action creator to redux to show it up in the right place
// 3 connect the component (container) by binding the action to component
// import the action creator into the component (container)
// import the function bindActionCreators from redux into the component (container)
// bindActionCreators is the function that makes action (generated by action creator) to flow throughout all the reducers of application
// bindActionCreators takse the return value from action creator and makes it flow throughout all reducers of application
